version: '3.9'

volumes:
  authservicevolume:
    name: authservice-volume
networks: 
  authservicenetwork:
    name: authservice-network

services:
  authservice-postgres:
    container_name: auth-pg
    image: postgres:13
    restart: on-failure
    env_file: 
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - authservicevolume:/var/lib/postgresql/data
      - ./database/scripts:/docker-entrypoint-initdb.d/
    networks:
      - authservicenetwork
  # authservice-pgadmin:
  #   container_name: auth-pgadmin
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment: 
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #   - "5050:80"
  #   networks: 
  #     - authservicenetwork
  authservice-api:
    container_name: auth-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    depends_on: 
     - authservice-postgres
    volumes:
      - ./:/app
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - authservicenetwork
    entrypoint: ["/bin/bash", "./scripts/entrypoint.dev.sh"]
